In [28]:
import numpy as np

In [29]:
lista =  [1, 2, 3] 
print(type(lista))

<class 'list'>


In [30]:
array = np.array(lista)
print(type(array))

<class 'numpy.ndarray'>


---
<h1 style="text-align:center;"> <strong>Dimensões e Tamanhos<strong> </h1>

In [31]:
print(f'len(lista) = {len(lista)}') # 3

len(lista) = 3


In [32]:
lista2 = [[1, 2, 3],[4, 5, 6]]
print(f'len(lista2) = {len(lista2)}')

len(lista2) = 2


In [33]:
lista3 = [[[1, 2, 3],[4, 5, 6]]]
print(f'len(lista3) = {len(lista3)}')

len(lista3) = 1


In [34]:
print(f'array.shape = {array.shape}')

array.shape = (3,)


In [35]:
array2 = np.array(lista2)
print(f'array2.shape = {array2.shape}')

array2.shape = (2, 3)


In [36]:
array3 = np.array(lista3)
print(f'array3.shape = {array3.shape}')

array3.shape = (1, 2, 3)


In [37]:
print(f'array2.ndim = {array2.ndim}')

array2.ndim = 2


---
<h1 style="text-align:center;"> <strong>Criando Arrays com Range<strong> </h1>

In [38]:
array = np.arange(0, 111, 10)
print(f'np.arange(0, 111, 10) = {array}')

np.arange(0, 111, 10) = [  0  10  20  30  40  50  60  70  80  90 100 110]


In [39]:
array = np.arange(1, 37)
array = np.reshape(array, (6, 6))
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [40]:
print(np.zeros((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
# Desafio 1

print(np.full((10, 10), True))

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [ ]:
print(np.linspace(0, 11, 9)) # Início, fim, quantidade

[ 0.     1.375  2.75   4.125  5.5    6.875  8.25   9.625 11.   ]


---
<h1 style="text-align:center;"> <strong>Criando Arrays com Random<strong> </h1>

In [47]:
print(np.random.rand(2, 2))

[[0.67691814 0.96184011]
 [0.32618542 0.09475119]]


In [50]:
print(np.random.randint(0, 10, 5))
print(np.random.randint(0, 10, (2, 2)))
print(np.random.randint(0, 50, 10).reshape(2, 5))

[6 8 9 4 1]
[[2 2]
 [3 2]]
[[ 9  8  0 23 11]
 [35 33 36 24 21]]


---
<h1 style="text-align:center;"> <strong>Extraindo valores das Arrays<strong> </h1>

In [ ]:
print('Valor máximo: ', array.max())
print('Valor mínimo: ', array.min())

Valor máximo:  36
Valor máximo:  1


In [54]:
print('Index de maior valor: ', array.argmax())
print('Index de menor valor: ', array.argmin())

Index de maior valor:  35
Index de menor valor:  0


In [57]:
print('Média de valores: ', array.mean())
print('Desvio de pdrão de valores: {:.2f}'.format(array.std()))
print('Variância de valores: {:.2f}'.format(array.var()))
print('Mediana de valores: ', np.median(array))


Média de valores:  18.5
Desvio de pdrão de valores: 10.39
Variância de valores: 107.92
Mediana de valores:  18.5


---
<h1 style="text-align:center;"> <strong>Extraindo valores dos Índices<strong> </h1>

In [67]:
lista = [[1, 2, 3],
         [4, 5, 6]]
print(lista[1][2])

array = np.array([[1, 2, 3], [4, 5, 6]])
print(array[1, 2])

6
6


In [69]:
array = np.array(range(0, 11))
print(array[array>3])

[ 4  5  6  7  8  9 10]


In [82]:
# Desafio 2
array = np.arange(1, 10).reshape((3, 3))
print(f'Tabela original: \n {array}')

array[array % 2 != 0] = 0
print(f'\nTabela substituta: \n {array}')



Tabela original: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Tabela substituta: 
 [[0 2 0]
 [4 0 6]
 [0 8 0]]


---
<h1 style="text-align:center;"> <strong>Cálculos matemáticos<strong> </h1>

In [94]:
a = np.random.randint(0, 50, 5)
b = np.random.randint(0, 50, 5)

print(a)
print(b)

[26 20 35 18 11]
[14  0 46 16  0]


In [95]:
print(a+10) # Soma com todos os elementos do array
print(np.sum(a)) # Retorna a soma de todos os valores

[36 30 45 28 21]
110


In [96]:
# Retorna lista com a soma entre os dois
print(a + b)
print(np.add(a,b))

[40 20 81 34 11]
[40 20 81 34 11]


In [97]:
# Retorna lista com a subtração entre os dois
print(a - b)
print(np.subtract(a,b))

[ 12  20 -11   2  11]
[ 12  20 -11   2  11]


In [100]:
print(a*b)
print(np.multiply(a, b))

[ 364    0 1610  288    0]
[ 364    0 1610  288    0]


In [ ]:
# Produto interno -> SOP

print(a @ b)
print(a.dot(b))


2262
2262


In [121]:
# Desafio 3

array = np.random.randint(0, 10, (2, 3)) # Crie um array de 2 linhas e 3 colunas
print(f'Crie um array de 2 linhas e 3 colunas:\n{array}')

array = array.reshape(3, 2) # Faça um reshape de 3 linhas e 2 colunas
print(f'Faça um reshape de 3 linhas e 2 colunas:\n{array}')

array[0, :] = array[0,:] + 5 # Some a primeira linha por 5
print(f'Some a primeira linha por 5:\n{array}')

array[1, :] = array[1,:] * 3 # Multiplque a segunda linha por 3
print(f'Multiplque a segunda linha por 3:\n{array}')

array[:, 1] = array[:,1] / 2 # Divida a segunda coluna por 2
print(f'Divida a segunda coluna por 2:\n{array}')

Crie um array de 2 linhas e 3 colunas:
[[0 2 1]
 [5 7 8]]
Faça um reshape de 3 linhas e 2 colunas:
[[0 2]
 [1 5]
 [7 8]]
Some a primeira linha por 5:
[[5 7]
 [1 5]
 [7 8]]
Multiplque a segunda linha por 3:
[[ 5  7]
 [ 3 15]
 [ 7  8]]
Divida a segunda coluna por 2:
[[5 3]
 [3 7]
 [7 4]]
